#
# board/renesas/rzg3s-dev/Makefile
#
# Copyright (C) 2022 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y	:= ../rcar-common/gen3-spl.o
else
obj-y	:= rzg3s-dev.o ../rcar-common/common.o
endif
