#
# board/renesas/rzv2m-dev/Makefile
#
# Copyright (C) 2022 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0+
#
obj-y	:= rzv2m-dev.o rzv2m-dev_cmn_cpg.o rzv2m-dev_common.o rzv2m-dev_sys.o rzv2m-dev_psc.o
