#
# board/renesas/rzt2h-dev/Makefile
#
# Copyright (C) 2023 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y	:= ../rcar-common/gen3-spl.o
else
obj-y	:= rzt2h-dev.o rzt2h-dev_eth.o ../rcar-common/common.o
endif
