#
# board/renesas/rzv2ma-dev/Makefile
#
# Copyright (C) 2022 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-y	:= rzv2ma-dev.o rzv2ma-dev_cmn_cpg.o rzv2ma-dev_common.o rzv2ma-dev_sys.o rzv2ma-dev_psc.o
