#
# board/renesas/rzv2ma-dev/Makefile
#
# Copyright (C) 2022 Renesas Electronics Corporation
#
# SPDX-License-Identifier: GPL-2.0+
#

obj-y	:= rzv2ma-dev.o evk_cmn_cpg.o evk_common.o evk_sys.o evk_psc.o
